// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: api/proto/activity.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActivityApiClient is the client API for ActivityApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityApiClient interface {
	GetActivity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Activity, error)
}

type activityApiClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityApiClient(cc grpc.ClientConnInterface) ActivityApiClient {
	return &activityApiClient{cc}
}

func (c *activityApiClient) GetActivity(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Activity, error) {
	out := new(Activity)
	err := c.cc.Invoke(ctx, "/activity.ActivityApi/GetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityApiServer is the server API for ActivityApi service.
// All implementations must embed UnimplementedActivityApiServer
// for forward compatibility
type ActivityApiServer interface {
	GetActivity(context.Context, *Empty) (*Activity, error)
	mustEmbedUnimplementedActivityApiServer()
}

// UnimplementedActivityApiServer must be embedded to have forward compatible implementations.
type UnimplementedActivityApiServer struct {
}

func (UnimplementedActivityApiServer) GetActivity(context.Context, *Empty) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedActivityApiServer) mustEmbedUnimplementedActivityApiServer() {}

// UnsafeActivityApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityApiServer will
// result in compilation errors.
type UnsafeActivityApiServer interface {
	mustEmbedUnimplementedActivityApiServer()
}

func RegisterActivityApiServer(s grpc.ServiceRegistrar, srv ActivityApiServer) {
	s.RegisterService(&ActivityApi_ServiceDesc, srv)
}

func _ActivityApi_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityApiServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activity.ActivityApi/GetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityApiServer).GetActivity(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityApi_ServiceDesc is the grpc.ServiceDesc for ActivityApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.ActivityApi",
	HandlerType: (*ActivityApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActivity",
			Handler:    _ActivityApi_GetActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/activity.proto",
}
